name: mtg_cards
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  go_router: ^3.0.4
  hive: ^2.0.6
  hover_effect: ^0.6.0
  intl: ^0.17.0
  json_annotation: ^4.4.0
  material_floating_search_bar: ^0.3.7
  skeletons: ^0.0.3

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - ./assets/icons/
